export const environment = {
  production: false,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGU5YmQyMC0zZWQ1LTQ1MzMtYTdlZi1iMWYwOWJhNjVkMzgiLCJlbWFpbCI6InRpYWdvQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJUaWFnbyBTYW50aW5pIiwibmJmIjoxNjk3NDY1NTc1LCJleHAiOjE2OTc0OTQzNzUsImlhdCI6MTY5NzQ2NTU3NSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.osWSS3oaP9RJMypqXwfIU_RwyU-NRoDrgbYgPPH3HH0',
};
