export const environment = {
  production: true,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWVkYzI2MS1iN2NkLTQ5YmUtOGRhZS1lMTgyNDJlMTNiZjYiLCJlbWFpbCI6ImRhdmlAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IkRhdmkiLCJuYmYiOjE2OTc1NTAwMzcsImV4cCI6MTY5NzU3ODgzNywiaWF0IjoxNjk3NTUwMDM3LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.PrQXylvlqWJc6weVfFn29LNJeVNvYFZRgiJZbWmPuZI',
};
